'''
Execute programs

This program needs the following directory structure:
- Contracts
- ContractsNew
    - Code
    - Locker.xlsx
    - main.py
- ContractsOld
'''
__author__ = "Lukas Beck"
__date__ = "09.12.2024"

from Code.add_contract import AddContract
from Code.extend_contract import ExtendContract
from Code.remove_contract import RemoveContracts
from Code.send_extend_reminder import SendExtendReminder

# Find file path and other global variables in ContractsNew\Code\lib\locker_parent.py

if __name__ == "__main__":
    while(True):
        print("This program handles interaction between spreadsheets and contracts, it can:"
            + "\nA: Add a contract"
            + "\nR: Remove a contract"
            + "\nE: Extending and reminding options"
            + "\n   Press enter to exit: "
            )
        choice = input("Please enter the letter for the wanted function (A/R/E): ").lower()
        if choice == "a":
            AddContract()
        elif choice == "r":
            RemoveContracts()
        elif choice == "e":
            print("In this menu you can: "
                + "\nE: Extend a specific contract"
                + "\nS: Send extend reminder to all contracts"
                + "\nG: Generate, save and export new extend codes for all contracts"
                + "\nU: Update the check-ins from a csl-list (generated by the website)"
                + "\n   Press enter to return to previous menu: "
                )
            choice = input("Please enter the letter for the wanted function (E/S/G/U): ").lower()
            if choice == "e":
                ExtendContract()
            elif choice == "s":
                SendExtendReminder()
            else:
                continue
        else:
            break
