'''
Execute programs

This program needs the following directory structure:
- Code
- Contracts
- ContractsOld
- Locker.xlsx
- main.py
'''
__author__ = "Lukas Beck"
__date__ = "31.10.2025"

from Code.add_contract import AddContract
from Code.extend_contract import ExtendContract
from Code.remove_contract import RemoveContracts
from Code.send_extend_reminder import SendExtendReminder
from Code.extend_code_generator import ExtendCodeGenerator
from Code.extend_update_from_file import ExtendUpdateFromFile

# Find file path and other global variables in \Code\lib\locker_parent.py

if __name__ == "__main__":
    while(True):
        print()
        print("This program handles interaction between spreadsheets and contracts, it can:"
            + "\nA: Add a contract"
            + "\nR: Remove a contract"
            + "\nE: Extending and reminding options"
            + "\n   Press enter to exit: "
            )
        choice = input("Please enter the letter for the wanted function (A/R/E): ").lower()
        if choice == "a":
            AddContract()
        elif choice == "r":
            RemoveContracts()
        elif choice == "e":
            print("In this menu you can: "
                + "\nE: Extend a specific contract"
                + "\nS: Send extend reminder to all contracts"
                + "\nG: Generate, save and export new extend codes for all contracts"
                + "\nU: Update the check-ins from a csv-list (generated by the website)"
                + "\n   Press enter to return to previous menu: "
                )
            choice = input("Please enter the letter for the wanted function (E/S/G/U): ").lower()
            if choice == "e":
                ExtendContract()
            elif choice == "s":
                SendExtendReminder()
            elif choice == "g":
                ExtendCodeGenerator()
            elif choice == "u":
                ExtendUpdateFromFile()
            else:
                continue
        else:
            break
